/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Page1Import } from './routes/page-1'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Page1Route = Page1Import.update({
  id: '/page-1',
  path: '/page-1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/page-1': {
      id: '/page-1'
      path: '/page-1'
      fullPath: '/page-1'
      preLoaderRoute: typeof Page1Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page-1': typeof Page1Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page-1': typeof Page1Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/page-1': typeof Page1Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page-1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page-1'
  id: '__root__' | '/' | '/page-1'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page1Route: typeof Page1Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page1Route: Page1Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/page-1"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/page-1": {
      "filePath": "page-1.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
